Fallback to multiple PGP servers

diff --git a/Dockerfile-debian.template b/Dockerfile-debian.template
--- a/Dockerfile-debian.template
+++ b/Dockerfile-debian.template
@@ -83,7 +83,17 @@ RUN set -eux; \
 		curl -fsSL -o php.tar.xz.asc "$PHP_ASC_URL"; \
 		export GNUPGHOME="$(mktemp -d)"; \
 		for key in $GPG_KEYS; do \
-			gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+			found=''; \
+			for server in \
+				ha.pool.sks-keyservers.net \
+				hkp://keyserver.ubuntu.com:80 \
+				hkp://p80.pool.sks-keyservers.net:80 \
+				pgp.mit.edu \
+			; do \
+				echo "Fetching GPG key $key from $server"; \
+				gpg --batch --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$key" && found=yes && break; \
+			done; \
+			test -z "$found" && echo >&2 "error: failed to fetch GPG key $key" && exit 1; \
 		done; \
 		gpg --batch --verify php.tar.xz.asc php.tar.xz; \
 		gpgconf --kill all; \
