:ambulance: Fix some BC break in ext install.
Fixes #266. Related to #256 changes.

diff --git a/docker-php-ext-install b/docker-php-ext-install
--- a/docker-php-ext-install
+++ b/docker-php-ext-install
@@ -39,11 +39,13 @@ for ext; do
 	if [ -z "$ext" ]; then
 		continue
 	fi
-	if ! grep -qE "^$ext$" /usr/src/php-available-exts; then
-		echo >&2 "error: /usr/src/php/ext/$ext does not exist"
-		echo >&2
-		usage >&2
-		exit 1
+	if ! grep -qE "^$ext$" /usr/src/php-available-exts ; then
+		if [ ! -d "/usr/src/php/ext/$ext" ] ; then
+			echo >&2 "error: /usr/src/php/ext/$ext does not exist"
+			echo >&2
+			usage >&2
+			exit 1
+		fi
 	fi
 	exts="$exts $ext"
 done
